updateProfile:
  handler: src/main/functions/profile/updateProfile.handler
  events:
    - httpApi:
        path: /profiles
        method: PUT
        authorizer:
          name: CognitoAuthorizer

updateProfilePhoto:
  handler: src/main/functions/profile/updateProfilePhoto.handler
  events:
    - httpApi:
        path: /profiles/photo
        method: POST
        authorizer:
          name: CognitoAuthorizer
